### ISSUE TITLE
Disciples Necropolis mobs need correct stats

### ISSUE THREAD

**Issue by UchihaSV** [L2jOrg/Datapack#13]
https://l2wiki.com/classic/The_Disciples_Necropolis - mob list

Mobs marked as `AUTO GENERATED NPC TODO: FIX IT`

Need set correct stats, especially **attack** and **defense**(not specified on the l2wiki)

**Comment by UchihaSV** [comment]
Catacomb of Dark Omens too need correct stats
https://l2wiki.com/classic/Catacomb_of_Dark_Omens  - mob list

**Comment by UchihaSV** [comment]
Why u close it?

In xml some of these monsters u can find patk **1950** and pdef **405** which have not changed since autogeneration:
```
<attack physical="1950.2231755595" magical="1331.5869440987" critical="4" attackSpeed="253" range="40"/>
<defence physical="405.85106382979" magical="297.0297029703"/>
```
You also can find these same values for many other monsters of different levels, which of course are incorrect.

**Comment by Forcecat01** [comment]
> 
> 
> Why u close it?
> 
> In xml some of these monsters u can find patk **1950** and pdef **405** which have not changed since autogeneration:
> 
> ```
> <attack physical="1950.2231755595" magical="1331.5869440987" critical="4" attackSpeed="253" range="40"/>
> <defence physical="405.85106382979" magical="297.0297029703"/>
> ```
> 
> You also can find these same values for many other monsters of different levels, which of course are incorrect.

attack and defense characteristics are working correctly. monsters have passive skills 

npc id="21904" level="76" type="Monster" name="Graveyard Prophet"

attack physical="1950.2231755595" magical="1331.5869440987" critical="4" attackSpeed="253" range="40" 
defence physical="405.85106382979" magical="297.0297029703"

###         <skillList>
            <skill id="4416" level="9" /> 
            <skill id="4408" level="14" /> 
            <skill id="4410" level="15" /> 
            <skill id="4411" level="14" /> 
            <skill id="4412" level="13" /> 
            <skill id="4413" level="14" /> 
            <skill id="4414" level="3" /> 
        </skillList>

![Screenshot_2](https://user-images.githubusercontent.com/54755997/111551865-3b9c3500-8792-11eb-88b2-dde91e5227d0.png)

Here, for example, a monster x1 whose passive skills and basic characteristics are less than monsters with catacombs x6 

npc id="20683" level="62" type="Monster" name="Vanor Silenos Scout"
attack physical="237.9049909" magical="178.7041" random="50" critical="1" accuracy="9" attackSpeed="253" type="BLUNT" range="40" distance="80" width="120"/>
defence physical="205.299259" magical="136.5719"/>

###         <skillList>
            <skill id="4032" level="4"/> 
            <skill id="4416" level="6"/> 
            <skill id="4410" level="10"/> 
            <skill id="4411" level="10"/> 
            <skill id="4412" level="12"/> 
            <skill id="4413" level="12"/> 
            <skill id="4085" level="1"/> 
        </skillList>

![Screenshot_3](https://user-images.githubusercontent.com/54755997/111552030-8b7afc00-8792-11eb-8352-f0fec6632be1.png)

I make the corrections that I have, the database contains information about the amount of hp, experience, and sp points, do you have official numbers, how much attack and defense should a particular monster have?

**Comment by Forcecat01** [comment]
now I will make the rest of the catacombs and necropolises, they now did not even have experience points and cn, so I need to fix it.
